agents:
  queue: hosted-mac-sm

env:
  GO_IMAGE: "golang:1.18.10"
  USER_NAME: "$(buildkite-agent meta-data get user-name)"

docker: &docker
  docker#v5.12.0:
    image: ${GO_IMAGE}
    mount-buildkite-agent: true
    propagate-environment: true

steps:
  - label: "Build and Upload Artifact"
    key: "build-step"
    command: go build -o hello/hello hello/hello.go
    plugins:
      - artifacts#v1.9.4:
          upload: hello/hello
      - *docker
  - input: "Name Input"
    key: "user-input-step"
    depends_on: ["build-step"]
    fields:
      - text: "Please input your name!"
        key: "user-name"
  - label: "Output user name"
    depends_on: ["user-input-step"]
    commands:
      - chmod +x ./hello/hello
      - ./hello/hello ${USER_NAME}
    plugins:
      - artifacts#v1.9.4:
          download: hello/hello
      - *docker
