agents:
  queue: hosted-linux-sm-arm

env:
  GO_IMAGE: "golang:1.18.10"

docker: &docker
  docker#v5.12.0:
    image: ${GO_IMAGE}
    mount-buildkite-agent: true
    propagate-environment: true

steps:
  - label: "Build and Upload Artifact"
    command: cd hello && go build -o ./my-hello-app
    key: "build-step"
    artifact_paths: "hello/my-hello-app"
    plugins:
      - *docker
  - input: "Name Input"
    fields:
      - text: "Please input your name!"
        key: "user-name"
    key: "user-input-step"
    depends_on: ["build-step"]
  - label: "Output user name"
    commands: |
      buildkite-agent artifact download hello/my-hello-app .
      cd hello
      chmod +x ./my-hello-app
      file ./my-hello-app 
      ./my-hello-app "$(buildkite-agent meta-data get user-name)"
    depends_on: ["user-input-step"]
    plugins:
      - *docker
