# # FOR HOSTED AGENT (REQUIRES PIPELINE SETING CLUSTER UPDATE)
agents:
  queue: hosted-mac-sm

steps:
  - label: 🔮 ponder stacks of orbs
    command: |
      brew install orbstack
      which docker
    key: pre-docker
  - label: 🐳 docker build stuff
    command: echo "hello, containerized world!"
    # command: cd hello && ls && go build -o ./my-hello-app
    key: "build-step"
    depends_on: ["pre-docker"]
    artifact_paths: "hello/my-hello-app"
    plugins:
      - docker#v5.11.0:
          image: "golang:1.18.0"
          mount-buildkite-agent: true
          debug: true
  # - input: "Name Input"
  #   fields:
  #     - text: "Please input your name!"
  #       key: "user-name"
  #   key: "user-input-step"
  #   depends_on: ["build-step"]
  # - label: "Output user name"
  #   commands: |
  #     buildkite-agent artifact download hello/my-hello-app .
  #     cd hello
  #     chmod +x ./my-hello-app
  #     file ./my-hello-app 
  #     ./my-hello-app "$(buildkite-agent meta-data get user-name)"
  #   depends_on: ["user-input-step"]
  #   plugins:
  #     - docker#v5.11.0:
  #         image: "golang:1.18.0"
  #         mount-buildkite-agent: true
  #         debug: true
